# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issue_comment:
    types: [created]
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    if: (github.event.issue.pull_request != '') && (contains(github.event.comment.body, '/override-bot')) && (github.repository == 'nunnatsa/temp')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        run: |
          date
