# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  collect-info:
    name: Prepare some data to consume later
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: create-date-info
        run: |
          BUILD_DATE_TIME=$(date +%Y-%m-%dT%H:%M:%S)
          echo "BUILD_DATE_TIME=${BUILD_DATE_TIME}" >> "$GITHUB_OUTPUT"
          echo "Generated build BUILD_DATE_TIME: ${BUILD_DATE_TIME}"
      - name: Get git ref
        id: get-git-ref
        run: |
          GIT_REF=${{ github.ref }}
          if [[ "${GIT_REF}" == "refs/heads/main" ]]; then
            GIT_REF="main"
          else
            GIT_REF=$(echo "${GIT_REF}" | sed 's|refs/heads/||')
          fi
          echo "GIT_REF=${GIT_REF}" >> "$GITHUB_OUTPUT"
          echo "Generated git ref: ${GIT_REF}"
  
  use-info:
    name: Use the data generated in the previous step
    runs-on: ubuntu-latest
    needs: collect-info
    steps:
      - name: Use the data from previous step
        run: |
          echo "Using the data collected in the previous step:"
          echo "Using BUILD_DATE_TIME=${{ steps.create-date-info.outputs.BUILD_DATE_TIME }}"
          echo "Using GIT_REF=${{ steps.get-git-ref.outputs.GIT_REF }}"

