# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: get current branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo ${{ github.ref }}

      - name: remove sanity-passed before starting
        run: gh issue edit "$NUMBER" --remove-label "sanity-passed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}

      - name: Run a multi-line script
        run: |
          if [[ -f testfile ]]; then
            gh issue edit "$NUMBER" --add-label "sanity-passed"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
