# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: echo main branch
        run: |
          if [[ ${{ github.event_name }} == "workflow_dispatch" && ${{ github.ref }} == "refs/heads/test" ]]; then
            echo "trigger = workflow_dispatch"
          fi
